import React, { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'en' | 'id';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations = {
  en: {
    // Header
    'nav.about': 'About Us',
    'nav.work': 'Our Work',
    'nav.projects': 'Projects',
    'nav.news': 'News',
    'nav.resources': 'Resources',
    'nav.contact': 'Contact',
    'nav.donate': 'Donate',
    
    // Hero
    'hero.title': 'Building harmony between people, forests and',
    'hero.climate': 'climate',
    'hero.subtitle': 'Empowering communities, preserving biodiversity, and promoting sustainable solutions throughout Indonesia',
    'hero.donateNow': 'Donate Now',
    'hero.exploreWork': 'Explore Our Work',
    'hero.activeUsers': 'Active Users',
    'hero.companies': 'Companies',
    'hero.co2Tracked': 'CO2 Tracked',
    
    // About
    'about.title': 'About Us',
    'about.subtitle': 'Working towards ecosystem balance and improved quality of life through forest preservation and community empowerment.',
    'about.vision.title': 'Our Vision',
    'about.vision.description': 'Building harmony between people, forests and climate through community empowerment, conservation and forest restoration to support sustainable economy, low carbon development and climate resilience.',
    'about.mission.title': 'Our Mission',
    'about.mission.point1': 'Protect Indonesia\'s forest biodiversity in collaboration with all stakeholders.',
    'about.mission.point2': 'Develop forest-based carbon management systems to finance conservation and improve community welfare.',
    'about.mission.point3': 'Facilitate inclusive social forestry models and ensure local/indigenous community rights.',
    'about.mission.point4': 'Promote policies supporting greenhouse gas emission reduction via forest restoration.',
    'about.mission.point5': 'Improve local community capacity through training on environmentally friendly agroforestry.',
    'about.team.title': 'Our Team',
    'about.team.description': 'A diverse group of environmental scientists, data analysts, and sustainability experts dedicated to creating impactful solutions.',
    'about.values.title': 'Our Values',
    'about.community.title': 'Community-Led Conservation',
    'about.community.description': 'We believe lasting conservation can only succeed when local and indigenous communities are the decision-makers and primary beneficiaries.',
    'about.science.title': 'Science-Based Approach',
    'about.science.description': 'Our strategies and methods are grounded in rigorous scientific research and best practices in ecology and natural resource management.',
    'about.transparency.title': 'Transparency & Accountability',
    'about.transparency.description': 'We maintain the highest standards of financial management and are committed to open communication with all our stakeholders.',
    'about.innovation.title': 'Innovation & Adaptability',
    'about.innovation.description': 'We embrace creative solutions and continuously adapt our approaches to address emerging challenges in conservation.',
    
    // Projects
    'projects.title': 'Our Projects',
    'projects.subtitle': 'Discover our impactful initiatives driving positive change for people and the planet',
    'projects.sumatra.title': 'Sumatra Forest Restoration',
    'projects.sumatra.description': 'Rehabilitating 5,000 hectares of degraded rainforest in North Sumatra through native species reforestation and community stewardship.',
    'projects.sumatra.impact': '5,000 hectares restored',
    'projects.agroforestry.title': 'Indigenous Agroforestry Development',
    'projects.agroforestry.description': 'Partnering with 12 indigenous communities to implement sustainable agroforestry systems that preserve biodiversity while enhancing livelihoods.',
    'projects.agroforestry.impact': '12 communities engaged',
    'projects.carbon.title': 'Carbon Offset Marketplace',
    'projects.carbon.description': 'Platform connecting businesses with verified carbon offset projects worldwide for immediate climate action.',
    'projects.carbon.impact': '500K tons offset',
    'projects.reforestation.title': 'Community Reforestation Program',
    'projects.reforestation.description': 'Engaging local communities in large-scale reforestation efforts to restore degraded forest landscapes.',
    'projects.reforestation.impact': '3,000 trees planted',
    'projects.category.forest': 'Forest',
    'projects.category.community': 'Community',
    'projects.category.technology': 'Technology',
    'projects.status.ongoing': 'Ongoing',
    'projects.status.beta': 'Beta',
    'projects.status.active': 'Active',
    'projects.status.completed': 'Completed',
    'projects.learnMore': 'Learn More',
    'projects.viewAll': 'View All Projects',
    
    // Contact
    'contact.title': 'Get in Touch',
    'contact.subtitle': 'Have questions or want to learn more about our work? We\'d love to hear from you',
    'contact.form.title': 'Send us a Message',
    'contact.form.name': 'Name',
    'contact.form.email': 'Email',
    'contact.form.company': 'Company/Organization',
    'contact.form.message': 'Message',
    'contact.form.placeholder': 'Tell us about your sustainability goals and how we can help...',
    'contact.form.send': 'Send Message',
    'contact.info.email.title': 'Email Us',
    'contact.info.phone.title': 'Call Us',
    'contact.info.phone.hours': 'Mon-Fri, 9am-6pm EST',
    'contact.info.address.title': 'Visit Us',
    'contact.info.address.text': 'Bekasi, West Java Province,\nIndonesia',
    
    // News
    'news.title': 'Latest News & Updates',
    'news.subtitle': 'Stay informed about our latest developments, partnerships, and insights in environmental sustainability and carbon tracking technology.',
    'news.item1.title': 'Sentani Reaches 1 Million Tons of CO2 Tracked',
    'news.item1.excerpt': 'A major milestone in our mission to make environmental impact visible and actionable for everyone.',
    'news.item2.title': 'New AI-Powered Emission Prediction Features',
    'news.item2.excerpt': 'Advanced machine learning algorithms now help predict future emissions based on current patterns and planned activities.',
    'news.item3.title': 'Partnership with Global Climate Initiative',
    'news.item3.excerpt': 'Sentani joins forces with leading environmental organizations to accelerate climate action worldwide.',
    'news.item4.title': 'Sustainable Business E-book Now Available',
    'news.item4.excerpt': 'Our comprehensive guide to implementing sustainable practices in modern business operations is now ready for download.',
    'news.categories.milestone': 'Milestone',
    'news.categories.productUpdate': 'Product Update',
    'news.categories.partnership': 'Partnership',
    'news.categories.resource': 'Resource',
    'news.filters.all': 'All News',
    'news.filters.productUpdates': 'Product Updates',
    'news.filters.partnerships': 'Partnerships',
    'news.filters.resources': 'Resources',
    
    // Resources
    'resources.title': 'Resources & E-books',
    'resources.subtitle': 'Access our comprehensive library of sustainability resources, including e-books, templates, and guides to help you on your environmental journey.',
    'resources.featured.badge': 'Featured E-book',
    'resources.featured.title': 'Sustainable Business Practices Guide',
    'resources.featured.description': 'Transform your business with our comprehensive 150-page e-book covering everything from carbon tracking to sustainable supply chain management.',
    'resources.featured.downloads': '2,500+ Downloads',
    'resources.featured.button': 'Purchase & Download',
    'resources.featured.imageAlt': 'E-book preview',
    'resources.items.ebook.title': 'Sustainable Business Practices E-book',
    'resources.items.ebook.description': 'Complete guide to implementing eco-friendly practices in your business operations.',
    'resources.items.template.title': 'Carbon Footprint Calculator Template',
    'resources.items.template.description': 'Excel template for calculating and tracking your organization\'s carbon emissions.',
    'resources.items.checklist.title': 'Environmental Compliance Checklist',
    'resources.items.checklist.description': 'Comprehensive checklist to ensure your business meets environmental regulations.',
    'resources.items.videoSeries.title': 'Video Series: Green Business Transformation',
    'resources.items.videoSeries.description': '10-part video series on transforming your business into a sustainable operation.',
    'resources.types.ebook': 'E-book',
    'resources.types.template': 'Template',
    'resources.types.guide': 'Guide',
    'resources.types.videoCourse': 'Video Course',
    'resources.pricing.free': 'Free',
    'resources.badges.featured': 'Featured',
    'resources.labels.downloads': 'downloads',
    'resources.buttons.buyNow': 'Buy Now',
    'resources.buttons.downloadFree': 'Download Free',
    'resources.buttons.purchaseNow': 'Purchase Now',
    'resources.freeSection.title': 'Free Resources',
    'resources.freeSection.description': 'Access our collection of free sustainability resources and stay updated with the latest environmental insights.',
    'resources.free.newsletter': 'Monthly Sustainability Newsletter',
    'resources.free.newsDigest': 'Weekly Environmental News Digest',
    'resources.free.bestPractices': 'Carbon Tracking Best Practices Guide',
    'resources.free.dashboard': 'Sustainability Metrics Dashboard Template',
    'resources.free.certification': 'Green Business Certification Roadmap',
    'resources.modal.whatYouGet': 'What You\'ll Get',
    'resources.modal.benefit1': 'Comprehensive 150-page guide',
    'resources.modal.benefit2': 'Actionable implementation strategies',
    'resources.modal.benefit3': 'Real-world case studies',
    'resources.modal.benefit4': 'Downloadable templates and checklists',
    'resources.modal.rating': '4.8/5 (120 reviews)',
    'resources.modal.instantDownload': 'Instant Download',
    'resources.messages.purchaseRedirect': 'You will be redirected to our secure payment processor.',

    // FAQ Section
    'faq.title': 'Frequently Asked Questions',
    'faq.contactTeam': 'Contact Our Team',
    'faq.noQuestionFound': "Don't see your question answered here?",
    'faq.question1': 'What is forest-based carbon management?',
    'faq.answer1': 'Forest-based carbon management refers to activities that enhance or maintain the carbon stored in forest ecosystems. This includes protecting existing forests to prevent carbon emissions, restoring degraded forests to sequester more carbon, and sustainable forest management practices. These activities can generate carbon credits that can be sold on voluntary or compliance carbon markets, providing financial incentives for conservation and community development.',
    'faq.question2': 'How does Sentani work with indigenous communities?',
    'faq.answer2': 'Sentani follows a rights-based approach to working with indigenous communities. We recognize and respect their customary rights to land and resources, traditional knowledge, and governance systems. Our partnerships with indigenous communities are based on principles of Free, Prior, and Informed Consent (FPIC). We collaborate on project planning and implementation, ensure equitable benefit sharing, strengthen community institutions, and support communities in securing legal recognition of their rights.',
    'faq.question3': 'What is agroforestry and how does it help conservation?',
    'faq.answer3': 'Agroforestry is a land use management system that combines trees or shrubs with crop cultivation and/or livestock. By integrating trees into agricultural landscapes, agroforestry helps maintain forest cover and connectivity, enhances biodiversity, improves soil health, and provides multiple income streams for communities. This reduces pressure on primary forests while building climate resilience and supporting sustainable livelihoods.',
    'faq.question4': 'Why are peatlands so important for climate change mitigation?',
    'faq.answer4': 'Peatlands are wetland ecosystems that contain thick layers of organic soil (peat) formed from partially decomposed plant material. Although they cover only 3% of Earth\'s land surface, they store nearly 30% of all soil carbon. Indonesian peatlands are particularly carbon-rich. When drained or burned, peatlands release massive amounts of greenhouse gases. Protecting and restoring peatlands is therefore a critical climate change mitigation strategy with high carbon benefits per hectare.',
    'faq.question5': 'How can I verify that my donation is being used effectively?',
    'faq.answer5': 'Sentani is committed to transparency and accountability in all our operations. We publish annual reports with detailed financial information and program outcomes, undergo regular external audits, and maintain open communication with donors. For major gifts, we can provide tailored reporting on the specific projects supported. We also welcome donors to visit our project sites when possible to see the impact of their contributions firsthand.',
    'faq.question6': 'What volunteer opportunities are available with Sentani?',
    'faq.answer6': 'We offer various volunteer opportunities depending on your skills, interests, and availability. These range from field-based roles supporting conservation activities and community engagement to professional services like communications, graphic design, translation, research, and technical expertise. Both in-person and remote volunteering options are available. Visit our Volunteer page for current opportunities and application details.',

    // Footer
    'footer.description': 'Building harmony between people, forests and climate',
    'footer.sections.organization': 'Organization',
    'footer.sections.resources': 'Resources',
    'footer.sections.support': 'Support',
    'footer.resources.ebooks': 'E-books',
    'footer.resources.templates': 'Templates',
    'footer.resources.guides': 'Guides',
    'footer.resources.blog': 'Blog',
    'footer.support.helpCenter': 'Help Center',
    'footer.support.privacy': 'Privacy Policy',
    'footer.support.terms': 'Terms of Service',
    'footer.email': 'admin@sentani.org',
    'footer.phone': '+62 8128 5905 342',
    'footer.location': 'Bekasi, West Java Province, Indonesia',
    'footer.copyright': '© 2024 Sentani. All rights reserved.',
    'footer.donateMission': 'Support Our Mission',

    // Common
    'common.back': 'Back',
    
    // Work Section
    'work.title': 'Our Work',
    'work.subtitle': 'Explore our key focus areas where we\'re making a difference in Indonesia\'s environmental landscape.',
    'work.approach.title': 'Our Approach',
    'work.approach.community.title': 'Community-Centered',
    'work.approach.community.description': 'We place local and indigenous communities at the center of all our initiatives, respecting traditional knowledge and customary rights.',
    'work.approach.holistic.title': 'Holistic & Integrated',
    'work.approach.holistic.description': 'We address environmental, social, and economic challenges through comprehensive, integrated approaches.',
    'work.approach.collaborative.title': 'Collaborative',
    'work.approach.collaborative.description': 'We forge partnerships across sectors - government, private, academic, and civil society - to maximize impact and sustainability.',
    'work.approach.rights.title': 'Rights-Based',
    'work.approach.rights.description': 'We uphold and advocate for the rights of local communities, ensuring equitable access to resources and benefits.',
    'work.approach.results.title': 'Results-Oriented',
    'work.approach.results.description': 'We focus on measurable outcomes and impact, continuously monitoring and evaluating our progress.',
    'work.approach.ecological.title': 'Ecologically Sound',
    'work.approach.ecological.description': 'We employ approaches that work with natural processes and enhance ecosystem functions.',
    
    'work.focus.title': 'Our Focus Areas',
    'work.focus.methodsInclude': 'Our methods include:',
    'work.focus.approachInclude': 'Our approach includes:',
    
    'work.focus.forest.title': 'Forest Conservation & Restoration',
    'work.focus.forest.description': 'Our forest conservation and restoration programs are at the heart of Sentani\'s work. Indonesia\'s forests are among the most biodiverse in the world, providing critical habitat for endangered species and ecosystem services for millions of people.',
    'work.focus.forest.method1': 'Natural regeneration facilitation',
    'work.focus.forest.method2': 'Native species reforestation',
    'work.focus.forest.method3': 'Community-based forest monitoring',
    'work.focus.forest.method4': 'Sustainable forest management training',
    'work.focus.forest.method5': 'Forest fire prevention and control',
    'work.focus.forest.method6': 'Biodiversity monitoring and research',
    'work.focus.forest.achievement': 'Through collaborative partnerships with government agencies, local communities, and other stakeholders, we\'ve targeted successfully protecting and restoring over 5,000 hectares of forest ecosystems across Indonesia.',
    
    'work.focus.agroforestry.title': 'Community Agroforestry',
    'work.focus.agroforestry.description': 'Our community agroforestry programs integrate traditional knowledge with modern sustainable farming techniques to create resilient food systems while protecting forest ecosystems.',
    'work.focus.agroforestry.explanation': 'Agroforestry combines trees and shrubs with crop cultivation and/or livestock systems. This approach helps diversify income sources for local communities while maintaining forest cover and enhancing biodiversity.',
    'work.focus.agroforestry.method1': 'Training on sustainable agroforestry techniques',
    'work.focus.agroforestry.method2': 'Establishing demonstration plots',
    'work.focus.agroforestry.method3': 'Developing value chains for sustainable forest products',
    'work.focus.agroforestry.method4': 'Creating market access for agroforestry products',
    'work.focus.agroforestry.method5': 'Seed and seedling distribution',
    'work.focus.agroforestry.method6': 'Farmer-to-farmer knowledge exchange',
    'work.focus.agroforestry.achievement': 'By working with over 75 indigenous communities targeted, we\'ve helped improve food security and increase income while maintaining forest cover on traditional lands.',
    
    'work.focus.peatland.title': 'Peatland Restoration',
    'work.focus.peatland.description': 'Indonesia\'s peatlands store enormous amounts of carbon and are critical for climate regulation. When degraded or burned, they release massive amounts of greenhouse gases. Our peatland protection work focuses on:',
    'work.focus.peatland.method1': 'Restoring hydrological functions through canal blocking and rewetting',
    'work.focus.peatland.method2': 'Reforestation of degraded peatland areas',
    'work.focus.peatland.method3': 'Community-based fire prevention and monitoring',
    'work.focus.peatland.method4': 'Sustainable livelihood development on peatlands',
    'work.focus.peatland.method5': 'Peatland mapping and carbon stock assessment',
    'work.focus.peatland.method6': 'Advocacy for peatland restoration policies',
    'work.focus.peatland.achievement': 'Through these interventions, we\'ve targeted reduce fire incidents by over 70% in our project areas and restored thousands of hectares of degraded peatlands. Our peatland work contributes significantly to Indonesia\'s climate change mitigation efforts.',
    
    'work.focus.carbon.title': 'Carbon Management & Climate Resilience',
    'work.focus.carbon.description': 'Our carbon management program leverages the economic value of forest carbon to finance conservation and community development. We develop high-quality forest carbon projects that generate verified carbon credits while protecting biodiversity and supporting local livelihoods.',
    'work.focus.carbon.method1': 'Forest carbon stock assessment and monitoring',
    'work.focus.carbon.method2': 'Development of forest protection and restoration projects under international standards (VCS, CCBS, etc.)',
    'work.focus.carbon.method3': 'Benefit-sharing mechanisms that ensure equitable distribution of carbon revenues',
    'work.focus.carbon.method4': 'Community capacity building for carbon project implementation',
    'work.focus.carbon.method5': 'Climate vulnerability assessments and adaptation planning',
    'work.focus.carbon.method6': 'Policy advocacy for forest-based climate solutions',
    
    'work.methodology.title': 'Our Methodology',
    'work.methodology.assessment.title': 'Assessment & Planning',
    'work.methodology.assessment.description': 'We begin each initiative with rigorous scientific assessment and participatory planning processes. This includes biodiversity surveys, social assessments, stakeholder consultations, and analysis of threats and opportunities. We develop detailed plans with measurable objectives, activities, and timelines.',
    'work.methodology.engagement.title': 'Community Engagement & Capacity Building',
    'work.methodology.engagement.description': 'We invest significant time in building relationships with local communities, understanding their needs and aspirations, and strengthening their capacity for sustainable resource management. This includes training, awareness-raising, and institutional development.',
    'work.methodology.implementation.title': 'Implementation & Adaptive Management',
    'work.methodology.implementation.description': 'Our field teams work closely with communities and local partners to implement planned activities. We employ adaptive management approaches, continuously monitoring progress and adjusting strategies as needed based on feedback and changing conditions.',
    'work.methodology.monitoring.title': 'Monitoring, Evaluation & Learning',
    'work.methodology.monitoring.description': 'We use robust monitoring systems to track ecological, social, and economic indicators of success. Regular evaluations help us assess impact, identify lessons learned, and improve our approaches. We share our learning through publications, workshops, and other knowledge exchange platforms.',
    'work.methodology.scaling.title': 'Scaling & Replication',
    'work.methodology.scaling.description': 'Successful approaches are documented and shared with government agencies, other NGOs, and relevant stakeholders to encourage adoption and scaling. We advocate for supportive policies and participate in networks and forums to spread effective conservation and development approaches.',
    
    // All Projects
    'allProjects.title': 'All Projects',
    'allProjects.subtitle': 'Discover our complete portfolio of environmental initiatives and sustainable development programs.',
    'allProjects.search': 'Search projects...',
    'allProjects.noResults': 'No projects found',
    'allProjects.tryDifferent': 'Try adjusting your search or filter criteria.',
    
    'allProjects.filters.all': 'All Projects',
    'allProjects.filters.corporate': 'Corporate',
    'allProjects.filters.municipal': 'Municipal',
    'allProjects.filters.education': 'Education',
    'allProjects.filters.technology': 'Technology',
    
    'allProjects.category.corporate': 'Corporate',
    'allProjects.category.municipal': 'Municipal',
    'allProjects.category.education': 'Education',
    'allProjects.category.technology': 'Technology',
    'allProjects.category.energy': 'Energy',
    'allProjects.category.agriculture': 'Agriculture',
    
    'allProjects.status.completed': 'Completed',
    'allProjects.status.ongoing': 'Ongoing',
    'allProjects.status.available': 'Available',
    'allProjects.status.beta': 'Beta',
    
    'allProjects.project1.title': 'Global Corporate Carbon Tracking',
    'allProjects.project1.description': 'Implemented comprehensive carbon tracking for 50+ multinational corporations, resulting in 30% average emissions reduction.',
    'allProjects.project1.impact': '2.5M tons CO2 reduced',
    
    'allProjects.project2.title': 'Smart City Sustainability Initiative',
    'allProjects.project2.description': 'Developed city-wide environmental monitoring system for urban sustainability planning and implementation.',
    'allProjects.project2.impact': '15 cities participating',
    
    'allProjects.project3.title': 'E-book: Sustainable Business Practices',
    'allProjects.project3.description': 'Comprehensive guide to implementing sustainable practices in modern business operations.',
    'allProjects.project3.impact': '10K+ downloads',
    
    'allProjects.project4.title': 'Carbon Offset Marketplace',
    'allProjects.project4.description': 'Platform connecting businesses with verified carbon offset projects worldwide for immediate climate action.',
    'allProjects.project4.impact': '500K tons offset',
    
    'allProjects.project5.title': 'Sustainable Supply Chain Analysis',
    'allProjects.project5.description': 'End-to-end supply chain sustainability assessment and optimization for manufacturing sector.',
    'allProjects.project5.impact': '35% reduced carbon footprint',
    
    'allProjects.project6.title': 'Renewable Energy Transition',
    'allProjects.project6.description': 'Strategic planning and implementation of renewable energy systems for industrial clients.',
    'allProjects.project6.impact': '60% reduction in fossil fuel use',
    
    'allProjects.project7.title': 'Sustainable Agriculture Initiative',
    'allProjects.project7.description': 'Regenerative farming practices implementation across 50,000 hectares of agricultural land.',
    'allProjects.project7.impact': '45% water usage reduction',
    
    'allProjects.project8.title': 'Zero Waste Office Program',
    'allProjects.project8.description': 'Comprehensive office waste reduction program for corporate environments.',
    'allProjects.project8.impact': '95% waste diversion rate'
  },
  id: {
    // Header
    'nav.about': 'Tentang Kami',
    'nav.work': 'Karya Kami',
    'nav.projects': 'Proyek',
    'nav.news': 'Berita',
    'nav.resources': 'Sumber Daya',
    'nav.contact': 'Kontak',
    'nav.donate': 'Donasi',
    
    // Hero
    'hero.title': 'Membangun harmoni antara manusia, hutan dan',
    'hero.climate': 'iklim',
    'hero.subtitle': 'Memberdayakan komunitas, melestarikan keanekaragaman hayati, dan mempromosikan solusi berkelanjutan di seluruh Indonesia',
    'hero.donateNow': 'Donasi Sekarang',
    'hero.exploreWork': 'Jelajahi Karya Kami',
    'hero.activeUsers': 'Pengguna Aktif',
    'hero.companies': 'Perusahaan',
    'hero.co2Tracked': 'CO2 Terlacak',
    
    // About
    'about.title': 'Tentang Kami',
    'about.subtitle': 'Bekerja menuju keseimbangan ekosistem dan peningkatan kualitas hidup melalui pelestarian hutan dan pemberdayaan komunitas.',
    'about.vision.title': 'Visi Kami',
    'about.vision.description': 'Membangun harmoni antara manusia, hutan dan iklim melalui pemberdayaan masyarakat, konservasi dan restorasi hutan untuk mendukung ekonomi berkelanjutan, pembangunan rendah karbon dan ketahanan iklim.',
    'about.mission.title': 'Misi Kami',
    'about.mission.point1': 'Melindungi keanekaragaman hayati hutan Indonesia dengan berkolaborasi dengan semua pemangku kepentingan.',
    'about.mission.point2': 'Mengembangkan sistem pengelolaan karbon berbasis hutan untuk membiayai konservasi dan meningkatkan kesejahteraan masyarakat.',
    'about.mission.point3': 'Memfasilitasi model perhutanan sosial yang inklusif dan memastikan hak-hak masyarakat lokal/adat.',
    'about.mission.point4': 'Mempromosikan kebijakan yang mendukung pengurangan emisi gas rumah kaca melalui restorasi hutan.',
    'about.mission.point5': 'Meningkatkan kapasitas masyarakat lokal melalui pelatihan agroforestri yang ramah lingkungan.',
    'about.team.title': 'Tim Kami',
    'about.team.description': 'Kelompok beragam ilmuwan lingkungan, analis data, dan ahli keberlanjutan yang berdedikasi menciptakan solusi berdampak.',
    'about.values.title': 'Nilai-Nilai Kami',
    'about.community.title': 'Konservasi yang Dipimpin Komunitas',
    'about.community.description': 'Kami percaya konservasi yang berkelanjutan hanya dapat berhasil ketika komunitas lokal dan adat menjadi pembuat keputusan dan penerima manfaat utama.',
    'about.science.title': 'Pendekatan Berbasis Sains',
    'about.science.description': 'Strategi dan metode kami didasarkan pada penelitian ilmiah yang ketat dan praktik terbaik dalam ekologi dan pengelolaan sumber daya alam.',
    'about.transparency.title': 'Transparansi & Akuntabilitas',
    'about.transparency.description': 'Kami mempertahankan standar tertinggi dalam pengelolaan keuangan dan berkomitmen pada komunikasi terbuka dengan semua pemangku kepentingan.',
    'about.innovation.title': 'Inovasi & Adaptabilitas',
    'about.innovation.description': 'Kami merangkul solusi kreatif dan terus menerus menyesuaikan pendekatan kami untuk mengatasi tantangan yang muncul dalam konservasi.',
    
    // Projects
    'projects.title': 'Proyek Kami',
    'projects.subtitle': 'Temukan inisiatif berdampak kami yang mendorong perubahan positif bagi manusia dan planet',
    'projects.sumatra.title': 'Restorasi Hutan Sumatera',
    'projects.sumatra.description': 'Merehabilitasi 5.000 hektar hutan hujan yang terdegradasi di Sumatera Utara melalui reboisasi spesies asli dan pengurusan komunitas.',
    'projects.sumatra.impact': '5.000 hektar dipulihkan',
    'projects.agroforestry.title': 'Pengembangan Agroforestri Masyarakat Adat',
    'projects.agroforestry.description': 'Bermitra dengan 12 komunitas adat untuk menerapkan sistem agroforestri berkelanjutan yang melestarikan keanekaragaman hayati sambil meningkatkan mata pencaharian.',
    'projects.agroforestry.impact': '12 komunitas terlibat',
    'projects.carbon.title': 'Pasar Offset Karbon',
    'projects.carbon.description': 'Platform yang menghubungkan bisnis dengan proyek offset karbon terverifikasi di seluruh dunia untuk aksi iklim segera.',
    'projects.carbon.impact': '500K ton offset',
    'projects.reforestation.title': 'Program Reboisasi Komunitas',
    'projects.reforestation.description': 'Melibatkan komunitas lokal dalam upaya reboisasi skala besar untuk memulihkan lanskap hutan yang terdegradasi.',
    'projects.reforestation.impact': '3.000 pohon ditanam',
    'projects.category.forest': 'Hutan',
    'projects.category.community': 'Komunitas',
    'projects.category.technology': 'Teknologi',
    'projects.status.ongoing': 'Berlangsung',
    'projects.status.beta': 'Beta',
    'projects.status.active': 'Aktif',
    'projects.status.completed': 'Selesai',
    'projects.learnMore': 'Pelajari Lebih Lanjut',
    'projects.viewAll': 'Lihat Semua Proyek',
    
    // Contact
    'contact.title': 'Hubungi Kami',
    'contact.subtitle': 'Ada pertanyaan atau ingin mempelajari lebih lanjut tentang karya kami? Kami senang mendengar dari Anda',
    'contact.form.title': 'Kirim Pesan kepada Kami',
    'contact.form.name': 'Nama',
    'contact.form.email': 'Email',
    'contact.form.company': 'Perusahaan/Organisasi',
    'contact.form.message': 'Pesan',
    'contact.form.placeholder': 'Ceritakan tentang tujuan keberlanjutan Anda dan bagaimana kami dapat membantu...',
    'contact.form.send': 'Kirim Pesan',
    'contact.info.email.title': 'Email Kami',
    'contact.info.phone.title': 'Telepon Kami',
    'contact.info.phone.hours': 'Sen-Jum, 9am-6pm EST',
    'contact.info.address.title': 'Kunjungi Kami',
    'contact.info.address.text': 'Bekasi, Provinsi Jawa Barat,\nIndonesia',
    
    // News
    'news.title': 'Berita & Pembaruan Terkini',
    'news.subtitle': 'Tetap terinformasi tentang perkembangan terbaru kami, kemitraan, dan wawasan dalam keberlanjutan lingkungan dan teknologi pelacakan karbon.',
    'news.item1.title': 'Sentani Mencapai 1 Juta Ton CO2 yang Dilacak',
    'news.item1.excerpt': 'Pencapaian penting dalam misi kami untuk membuat dampak lingkungan terlihat dan dapat ditindaklanjuti untuk semua orang.',
    'news.item2.title': 'Fitur Prediksi Emisi Bertenaga AI Terbaru',
    'news.item2.excerpt': 'Algoritma pembelajaran mesin canggih kini membantu memprediksi emisi masa depan berdasarkan pola dan aktivitas yang direncanakan saat ini.',
    'news.item3.title': 'Kemitraan dengan Inisiatif Iklim Global',
    'news.item3.excerpt': 'Sentani bergabung dengan organisasi lingkungan terkemuka untuk mempercepat aksi iklim di seluruh dunia.',
    'news.item4.title': 'E-book Bisnis Berkelanjutan Kini Tersedia',
    'news.item4.excerpt': 'Panduan komprehensif kami untuk menerapkan praktik berkelanjutan dalam operasi bisnis modern kini siap diunduh.',
    'news.categories.milestone': 'Pencapaian',
    'news.categories.productUpdate': 'Pembaruan Produk',
    'news.categories.partnership': 'Kemitraan',
    'news.categories.resource': 'Sumber Daya',
    'news.filters.all': 'Semua Berita',
    'news.filters.productUpdates': 'Pembaruan Produk',
    'news.filters.partnerships': 'Kemitraan',
    'news.filters.resources': 'Sumber Daya',
    
    // Resources
    'resources.title': 'Sumber Daya & E-book',
    'resources.subtitle': 'Akses perpustakaan komprehensif sumber daya keberlanjutan kami, termasuk e-book, template, dan panduan untuk membantu perjalanan lingkungan Anda.',
    'resources.featured.badge': 'E-book Unggulan',
    'resources.featured.title': 'Panduan Praktik Bisnis Berkelanjutan',
    'resources.featured.description': 'Transformasikan bisnis Anda dengan e-book komprehensif 150 halaman kami yang mencakup segala hal mulai dari pelacakan karbon hingga manajemen rantai pasokan berkelanjutan.',
    'resources.featured.downloads': '2.500+ Unduhan',
    'resources.featured.button': 'Beli & Unduh',
    'resources.featured.imageAlt': 'Pratinjau e-book',
    'resources.items.ebook.title': 'E-book Praktik Bisnis Berkelanjutan',
    'resources.items.ebook.description': 'Panduan lengkap untuk menerapkan praktik ramah lingkungan dalam operasi bisnis Anda.',
    'resources.items.template.title': 'Template Kalkulator Jejak Karbon',
    'resources.items.template.description': 'Template Excel untuk menghitung dan melacak emisi karbon organisasi Anda.',
    'resources.items.checklist.title': 'Daftar Periksa Kepatuhan Lingkungan',
    'resources.items.checklist.description': 'Daftar periksa komprehensif untuk memastikan bisnis Anda memenuhi regulasi lingkungan.',
    'resources.items.videoSeries.title': 'Seri Video: Transformasi Bisnis Hijau',
    'resources.items.videoSeries.description': 'Seri video 10 bagian tentang mentransformasi bisnis Anda menjadi operasi berkelanjutan.',
    'resources.types.ebook': 'E-book',
    'resources.types.template': 'Template',
    'resources.types.guide': 'Panduan',
    'resources.types.videoCourse': 'Kursus Video',
    'resources.pricing.free': 'Gratis',
    'resources.badges.featured': 'Unggulan',
    'resources.labels.downloads': 'unduhan',
    'resources.buttons.buyNow': 'Beli Sekarang',
    'resources.buttons.downloadFree': 'Unduh Gratis',
    'resources.buttons.purchaseNow': 'Beli Sekarang',
    'resources.freeSection.title': 'Sumber Daya Gratis',
    'resources.freeSection.description': 'Akses koleksi sumber daya keberlanjutan gratis kami dan tetap update dengan wawasan lingkungan terbaru.',
    'resources.free.newsletter': 'Newsletter Keberlanjutan Bulanan',
    'resources.free.newsDigest': 'Ringkasan Berita Lingkungan Mingguan',
    'resources.free.bestPractices': 'Panduan Praktik Terbaik Pelacakan Karbon',
    'resources.free.dashboard': 'Template Dashboard Metrik Keberlanjutan',
    'resources.free.certification': 'Peta Jalan Sertifikasi Bisnis Hijau',
    'resources.modal.whatYouGet': 'Yang Akan Anda Dapatkan',
    'resources.modal.benefit1': 'Panduan komprehensif 150 halaman',
    'resources.modal.benefit2': 'Strategi implementasi yang dapat ditindaklanjuti',
    'resources.modal.benefit3': 'Studi kasus dunia nyata',
    'resources.modal.benefit4': 'Template dan daftar periksa yang dapat diunduh',
    'resources.modal.rating': '4,8/5 (120 ulasan)',
    'resources.modal.instantDownload': 'Unduh Instan',
    'resources.messages.purchaseRedirect': 'Anda akan diarahkan ke prosesor pembayaran aman kami.',

    // FAQ Section
    'faq.title': 'Pertanyaan yang Sering Diajukan',
    'faq.contactTeam': 'Hubungi Tim Kami',
    'faq.noQuestionFound': 'Tidak menemukan pertanyaan Anda di sini?',
    'faq.question1': 'Apa itu manajemen karbon berbasis hutan?',
    'faq.answer1': 'Manajemen karbon berbasis hutan mengacu pada kegiatan yang meningkatkan atau mempertahankan karbon yang tersimpan dalam ekosistem hutan. Ini termasuk melindungi hutan yang ada untuk mencegah emisi karbon, memulihkan hutan yang terdegradasi untuk menyerap lebih banyak karbon, dan praktik pengelolaan hutan berkelanjutan. Kegiatan ini dapat menghasilkan kredit karbon yang dapat dijual di pasar karbon sukarela atau kepatuhan, memberikan insentif finansial untuk konservasi dan pembangunan komunitas.',
    'faq.question2': 'Bagaimana Sentani bekerja dengan komunitas adat?',
    'faq.answer2': 'Sentani mengikuti pendekatan berbasis hak dalam bekerja dengan komunitas adat. Kami mengakui dan menghormati hak adat mereka atas tanah dan sumber daya, pengetahuan tradisional, dan sistem tata kelola. Kemitraan kami dengan komunitas adat didasarkan pada prinsip Persetujuan Bebas, Didahulukan, dan Diinformasikan (FPIC). Kami berkolaborasi dalam perencanaan dan implementasi proyek, memastikan pembagian manfaat yang adil, memperkuat institusi komunitas, dan mendukung komunitas dalam mengamankan pengakuan hukum atas hak-hak mereka.',
    'faq.question3': 'Apa itu agroforestri dan bagaimana membantu konservasi?',
    'faq.answer3': 'Agroforestri adalah sistem pengelolaan penggunaan lahan yang menggabungkan pohon atau semak dengan budidaya tanaman dan/atau peternakan. Dengan mengintegrasikan pohon ke dalam lanskap pertanian, agroforestri membantu mempertahankan tutupan dan konektivitas hutan, meningkatkan keanekaragaman hayati, memperbaiki kesehatan tanah, dan menyediakan multiple sumber pendapatan bagi komunitas. Ini mengurangi tekanan pada hutan primer sambil membangun ketahanan iklim dan mendukung mata pencaharian berkelanjutan.',
    'faq.question4': 'Mengapa lahan gambut sangat penting untuk mitigasi perubahan iklim?',
    'faq.answer4': 'Lahan gambut adalah ekosistem lahan basah yang mengandung lapisan tanah organik tebal (gambut) yang terbentuk dari bahan tanaman yang terdekomposisi sebagian. Meskipun hanya menutupi 3% dari permukaan tanah Bumi, mereka menyimpan hampir 30% dari semua karbon tanah. Lahan gambut Indonesia sangat kaya karbon. Ketika dikeringkan atau dibakar, lahan gambut melepaskan gas rumah kaca dalam jumlah besar. Melindungi dan memulihkan lahan gambut oleh karena itu merupakan strategi mitigasi perubahan iklim yang kritis dengan manfaat karbon tinggi per hektar.',
    'faq.question5': 'Bagaimana saya dapat memverifikasi bahwa donasi saya digunakan secara efektif?',
    'faq.answer5': 'Sentani berkomitmen pada transparansi dan akuntabilitas dalam semua operasi kami. Kami menerbitkan laporan tahunan dengan informasi keuangan terperinci dan hasil program, menjalani audit eksternal reguler, dan mempertahankan komunikasi terbuka dengan para donatur. Untuk sumbangan besar, kami dapat menyediakan pelaporan yang disesuaikan dengan proyek-proyek tertentu yang didukung. Kami juga menyambut para donatur untuk mengunjungi lokasi proyek kami bila memungkinkan untuk melihat dampak kontribusi mereka secara langsung.',
    'faq.question6': 'Kesempatan relawan apa yang tersedia dengan Sentani?',
    'faq.answer6': 'Kami menawarkan berbagai kesempatan relawan tergantung pada keterampilan, minat, dan ketersediaan Anda. Ini berkisar dari peran berbasis lapangan yang mendukung kegiatan konservasi dan keterlibatan komunitas hingga layanan profesional seperti komunikasi, desain grafis, terjemahan, penelitian, dan keahlian teknis. Tersedia opsi relawan tatap muka dan jarak jauh. Kunjungi halaman Relawan kami untuk kesempatan terkini dan detail aplikasi.',

    // Footer
    'footer.description': 'Membangun harmoni antara manusia, hutan dan iklim',
    'footer.sections.organization': 'Organisasi',
    'footer.sections.resources': 'Sumber Daya',
    'footer.sections.support': 'Dukungan',
    'footer.resources.ebooks': 'E-book',
    'footer.resources.templates': 'Template',
    'footer.resources.guides': 'Panduan',
    'footer.resources.blog': 'Blog',
    'footer.support.helpCenter': 'Pusat Bantuan',
    'footer.support.privacy': 'Kebijakan Privasi',
    'footer.support.terms': 'Syarat Layanan',
    'footer.email': 'admin@sentani.org',
    'footer.phone': '+62 8128 5905 342',
    'footer.location': 'Bekasi, Provinsi Jawa Barat, Indonesia',
    'footer.copyright': '© 2024 Sentani. Hak cipta dilindungi.',
    'footer.donateMission': 'Dukung Misi Kami',

    // Common
    'common.back': 'Kembali',
    
    // Work Section
    'work.title': 'Karya Kami',
    'work.subtitle': 'Jelajahi area fokus utama kami dimana kami membuat perbedaan dalam lanskap lingkungan Indonesia.',
    'work.approach.title': 'Pendekatan Kami',
    'work.approach.community.title': 'Berpusat pada Komunitas',
    'work.approach.community.description': 'Kami menempatkan komunitas lokal dan adat sebagai pusat dari semua inisiatif kami, menghormati pengetahuan tradisional dan hak-hak adat.',
    'work.approach.holistic.title': 'Holistik & Terintegrasi',
    'work.approach.holistic.description': 'Kami mengatasi tantangan lingkungan, sosial, dan ekonomi melalui pendekatan yang komprehensif dan terintegrasi.',
    'work.approach.collaborative.title': 'Kolaboratif',
    'work.approach.collaborative.description': 'Kami menjalin kemitraan lintas sektor - pemerintah, swasta, akademik, dan masyarakat sipil - untuk memaksimalkan dampak dan keberlanjutan.',
    'work.approach.rights.title': 'Berbasis Hak',
    'work.approach.rights.description': 'Kami menjunjung tinggi dan memperjuangkan hak-hak komunitas lokal, memastikan akses yang adil terhadap sumber daya dan manfaat.',
    'work.approach.results.title': 'Berorientasi Hasil',
    'work.approach.results.description': 'Kami fokus pada hasil yang dapat diukur dan dampak, terus memantau dan mengevaluasi kemajuan kami.',
    'work.approach.ecological.title': 'Secara Ekologis Sehat',
    'work.approach.ecological.description': 'Kami menggunakan pendekatan yang bekerja dengan proses alami dan meningkatkan fungsi ekosistem.',
    
    'work.focus.title': 'Area Fokus Kami',
    'work.focus.methodsInclude': 'Metode kami meliputi:',
    'work.focus.approachInclude': 'Pendekatan kami meliputi:',
    
    'work.focus.forest.title': 'Konservasi & Restorasi Hutan',
    'work.focus.forest.description': 'Program konservasi dan restorasi hutan kami adalah inti dari karya Sentani. Hutan Indonesia termasuk yang paling beragam secara biologis di dunia, menyediakan habitat penting bagi spesies terancam dan layanan ekosistem bagi jutaan orang.',
    'work.focus.forest.method1': 'Fasilitasi regenerasi alami',
    'work.focus.forest.method2': 'Reboisasi spesies asli',
    'work.focus.forest.method3': 'Pemantauan hutan berbasis komunitas',
    'work.focus.forest.method4': 'Pelatihan pengelolaan hutan berkelanjutan',
    'work.focus.forest.method5': 'Pencegahan dan pengendalian kebakaran hutan',
    'work.focus.forest.method6': 'Pemantauan keanekaragaman hayati dan penelitian',
    'work.focus.forest.achievement': 'Melalui kemitraan kolaboratif dengan lembaga pemerintah, komunitas lokal, dan pemangku kepentingan lainnya, kami telah menargetkan berhasil melindungi dan memulihkan lebih dari 5.000 hektar ekosistem hutan di seluruh Indonesia.',
    
    'work.focus.agroforestry.title': 'Agroforestri Komunitas',
    'work.focus.agroforestry.description': 'Program agroforestri komunitas kami mengintegrasikan pengetahuan tradisional dengan teknik pertanian berkelanjutan modern untuk menciptakan sistem pangan yang tangguh sambil melindungi ekosistem hutan.',
    'work.focus.agroforestry.explanation': 'Agroforestri menggabungkan pohon dan semak dengan budidaya tanaman dan/atau sistem peternakan. Pendekatan ini membantu diversifikasi sumber pendapatan bagi komunitas lokal sambil mempertahankan tutupan hutan dan meningkatkan keanekaragaman hayati.',
    'work.focus.agroforestry.method1': 'Pelatihan tentang teknik agroforestri berkelanjutan',
    'work.focus.agroforestry.method2': 'Mendirikan plot demonstrasi',
    'work.focus.agroforestry.method3': 'Mengembangkan rantai nilai untuk produk hutan berkelanjutan',
    'work.focus.agroforestry.method4': 'Menciptakan akses pasar untuk produk agroforestri',
    'work.focus.agroforestry.method5': 'Distribusi benih dan bibit',
    'work.focus.agroforestry.method6': 'Pertukaran pengetahuan petani ke petani',
    'work.focus.agroforestry.achievement': 'Dengan bekerja dengan lebih dari 75 komunitas adat yang ditargetkan, kami telah membantu meningkatkan ketahanan pangan dan meningkatkan pendapatan sambil mempertahankan tutupan hutan di tanah tradisional.',
    
    'work.focus.peatland.title': 'Restorasi Lahan Gambut',
    'work.focus.peatland.description': 'Lahan gambut Indonesia menyimpan karbon dalam jumlah besar dan sangat penting untuk regulasi iklim. Ketika terdegradasi atau terbakar, mereka melepaskan gas rumah kaca dalam jumlah besar. Karya perlindungan lahan gambut kami berfokus pada:',
    'work.focus.peatland.method1': 'Memulihkan fungsi hidrologi melalui penyumbatan kanal dan pembasahan kembali',
    'work.focus.peatland.method2': 'Reboisasi area lahan gambut yang terdegradasi',
    'work.focus.peatland.method3': 'Pencegahan dan pemantauan kebakaran berbasis komunitas',
    'work.focus.peatland.method4': 'Pengembangan mata pencaharian berkelanjutan di lahan gambut',
    'work.focus.peatland.method5': 'Pemetaan lahan gambut dan penilaian stok karbon',
    'work.focus.peatland.method6': 'Advokasi untuk kebijakan restorasi lahan gambut',
    'work.focus.peatland.achievement': 'Melalui intervensi ini, kami telah menargetkan mengurangi insiden kebakaran lebih dari 70% di area proyek kami dan memulihkan ribuan hektar lahan gambut yang terdegradasi. Karya lahan gambut kami berkontribusi signifikan terhadap upaya mitigasi perubahan iklim Indonesia.',
    
    'work.focus.carbon.title': 'Manajemen Karbon & Ketahanan Iklim',
    'work.focus.carbon.description': 'Program manajemen karbon kami memanfaatkan nilai ekonomi karbon hutan untuk membiayai konservasi dan pembangunan komunitas. Kami mengembangkan proyek karbon hutan berkualitas tinggi yang menghasilkan kredit karbon terverifikasi sambil melindungi keanekaragaman hayati dan mendukung mata pencaharian lokal.',
    'work.focus.carbon.method1': 'Penilaian dan pemantauan stok karbon hutan',
    'work.focus.carbon.method2': 'Pengembangan proyek perlindungan dan restorasi hutan di bawah standar internasional (VCS, CCBS, dll.)',
    'work.focus.carbon.method3': 'Mekanisme pembagian manfaat yang memastikan distribusi pendapatan karbon yang adil',
    'work.focus.carbon.method4': 'Pembangunan kapasitas komunitas untuk implementasi proyek karbon',
    'work.focus.carbon.method5': 'Penilaian kerentanan iklim dan perencanaan adaptasi',
    'work.focus.carbon.method6': 'Advokasi kebijakan untuk solusi iklim berbasis hutan',
    
    'work.methodology.title': 'Metodologi Kami',
    'work.methodology.assessment.title': 'Penilaian & Perencanaan',
    'work.methodology.assessment.description': 'Kami memulai setiap inisiatif dengan penilaian ilmiah yang ketat dan proses perencanaan partisipatif. Ini termasuk survei keanekaragaman hayati, penilaian sosial, konsultasi pemangku kepentingan, dan analisis ancaman dan peluang. Kami mengembangkan rencana rinci dengan tujuan, aktivitas, dan jadwal yang dapat diukur.',
    'work.methodology.engagement.title': 'Keterlibatan Komunitas & Pembangunan Kapasitas',
    'work.methodology.engagement.description': 'Kami menginvestasikan waktu yang signifikan dalam membangun hubungan dengan komunitas lokal, memahami kebutuhan dan aspirasi mereka, dan memperkuat kapasitas mereka untuk pengelolaan sumber daya berkelanjutan. Ini termasuk pelatihan, peningkatan kesadaran, dan pembangunan institusi.',
    'work.methodology.implementation.title': 'Implementasi & Manajemen Adaptif',
    'work.methodology.implementation.description': 'Tim lapangan kami bekerja erat dengan komunitas dan mitra lokal untuk mengimplementasikan aktivitas yang direncanakan. Kami menggunakan pendekatan manajemen adaptif, terus memantau kemajuan dan menyesuaikan strategi sesuai kebutuhan berdasarkan umpan balik dan kondisi yang berubah.',
    'work.methodology.monitoring.title': 'Pemantauan, Evaluasi & Pembelajaran',
    'work.methodology.monitoring.description': 'Kami menggunakan sistem pemantauan yang kuat untuk melacak indikator ekologis, sosial, dan ekonomi kesuksesan. Evaluasi rutin membantu kami menilai dampak, mengidentifikasi pelajaran yang dipetik, dan meningkatkan pendekatan kami. Kami berbagi pembelajaran melalui publikasi, workshop, dan platform pertukaran pengetahuan lainnya.',
    'work.methodology.scaling.title': 'Penskalaan & Replikasi',
    'work.methodology.scaling.description': 'Pendekatan yang berhasil didokumentasikan dan dibagikan dengan lembaga pemerintah, LSM lain, dan pemangku kepentingan terkait untuk mendorong adopsi dan penskalaan. Kami mengadvokasi kebijakan yang mendukung dan berpartisipasi dalam jaringan dan forum untuk menyebarkan pendekatan konservasi dan pembangunan yang efektif.',
    
    // All Projects
    'allProjects.title': 'Semua Proyek',
    'allProjects.subtitle': 'Temukan portofolio lengkap inisiatif lingkungan dan program pembangunan berkelanjutan kami.',
    'allProjects.search': 'Cari proyek...',
    'allProjects.noResults': 'Tidak ada proyek ditemukan',
    'allProjects.tryDifferent': 'Coba sesuaikan kriteria pencarian atau filter Anda.',
    
    'allProjects.filters.all': 'Semua Proyek',
    'allProjects.filters.corporate': 'Korporat',
    'allProjects.filters.municipal': 'Pemerintah Daerah',
    'allProjects.filters.education': 'Pendidikan',
    'allProjects.filters.technology': 'Teknologi',
    
    'allProjects.category.corporate': 'Korporat',
    'allProjects.category.municipal': 'Pemerintah Daerah',
    'allProjects.category.education': 'Pendidikan',
    'allProjects.category.technology': 'Teknologi',
    'allProjects.category.energy': 'Energi',
    'allProjects.category.agriculture': 'Pertanian',
    
    'allProjects.status.completed': 'Selesai',
    'allProjects.status.ongoing': 'Berlangsung',
    'allProjects.status.available': 'Tersedia',
    'allProjects.status.beta': 'Beta',
    
    'allProjects.project1.title': 'Pelacakan Karbon Korporat Global',
    'allProjects.project1.description': 'Mengimplementasikan pelacakan karbon komprehensif untuk 50+ perusahaan multinasional, menghasilkan rata-rata pengurangan emisi 30%.',
    'allProjects.project1.impact': '2,5M ton CO2 dikurangi',
    
    'allProjects.project2.title': 'Inisiatif Keberlanjutan Kota Pintar',
    'allProjects.project2.description': 'Mengembangkan sistem pemantauan lingkungan seluruh kota untuk perencanaan dan implementasi keberlanjutan perkotaan.',
    'allProjects.project2.impact': '15 kota berpartisipasi',
    
    'allProjects.project3.title': 'E-book: Praktik Bisnis Berkelanjutan',
    'allProjects.project3.description': 'Panduan komprehensif untuk mengimplementasikan praktik berkelanjutan dalam operasi bisnis modern.',
    'allProjects.project3.impact': '10K+ unduhan',
    
    'allProjects.project4.title': 'Pasar Offset Karbon',
    'allProjects.project4.description': 'Platform yang menghubungkan bisnis dengan proyek offset karbon terverifikasi di seluruh dunia untuk aksi iklim segera.',
    'allProjects.project4.impact': '500K ton offset',
    
    'allProjects.project5.title': 'Analisis Rantai Pasokan Berkelanjutan',
    'allProjects.project5.description': 'Penilaian dan optimasi keberlanjutan rantai pasokan end-to-end untuk sektor manufaktur.',
    'allProjects.project5.impact': '35% jejak karbon berkurang',
    
    'allProjects.project6.title': 'Transisi Energi Terbarukan',
    'allProjects.project6.description': 'Perencanaan strategis dan implementasi sistem energi terbarukan untuk klien industri.',
    'allProjects.project6.impact': '60% pengurangan penggunaan bahan bakar fosil',
    
    'allProjects.project7.title': 'Inisiatif Pertanian Berkelanjutan',
    'allProjects.project7.description': 'Implementasi praktik pertanian regeneratif di 50.000 hektar lahan pertanian.',
    'allProjects.project7.impact': '45% pengurangan penggunaan air',
    
    'allProjects.project8.title': 'Program Kantor Tanpa Limbah',
    'allProjects.project8.description': 'Program pengurangan limbah kantor komprehensif untuk lingkungan korporat.',
    'allProjects.project8.impact': '95% tingkat pengalihan limbah'
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('en');

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

export default LanguageContext;
