backend:
  name: github
  repo: harripao/eco-track-headless-forge
  branch: main
  auth_scope: repo
  client_id: Ov23lijQSjaIr9oUjHbe
  base_url: https://reliable-sunshine-83aea0.netlify.app

media_folder: "assets/images"
public_folder: "/assets/images"

collections:
  - name: "pages"
    label: "Pages"
    folder: "content"
    create: true
    slug: "{{slug}}"
    identifier_field: title
    summary: "{{title}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
