backend:
  name: github
  repo: harripao/eco-track-headless-forge
  branch: main
  commit_messages:
    create: "Create {{collection}}: {{slug}}"
    update: "Update {{collection}}: {{slug}}"
    delete: "Delete {{collection}}: {{slug}}"

media_folder: "assets"
public_folder: "/assets"

media_library:
  name: local

collections:
  - name: pages
    label: Pages
    folder: content
    create: true
    slug: "{{slug}}"
    identifier_field: title
    summary: "{{title}}"
    fields:
      - label: Title
        name: title
        widget: string
      - label: Body
        name: body
        widget: markdown
editor:
  preview: false
publish_mode: editorial_workflow